version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    env_file:
      - .env.spring
    networks:
      - app-network
    restart: unless-stopped

  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    env_file:
      - .env.python
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge